services:
  api:
    build: .
    container_name: hackrx
    env_file:
      - .env
    ports:
      - "4004:4004"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 4004 --reload