services:
  api:
    build: .
    container_name: hackrx_api
    env_file:
      - .env
    ports:
      - "4004:4004"
    volumes:
      - .:/app
    # This command first makes the script executable, then runs it.
    command: sh -c "chmod +x /app/start.sh && /app/start.sh"
    depends_on:
      - redis
    networks:
      - internal_network

  redis:
    image: "redis:alpine"
    container_name: hackrx_redis
    networks:
      - internal_network
    volumes:
      - redis_data:/data

networks:
  internal_network:
    driver: bridge

volumes:
  redis_data: