services:
  api:
    build: .
    container_name: hackrx_api
    env_file:
      - .env
    ports:
      - "4004:4004"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 4004 --reload
    depends_on:
      - redis
    networks:
      - internal_network

  redis:
    image: "redis:alpine"
    container_name: hackrx_redis
    networks:
      - internal_network
    volumes:
      - redis_data:/data

networks:
  internal_network:
    driver: bridge

volumes:
  redis_data: